import { Flow } from '../flows/flow-post-processor';

/**
 * System prompt
 */
export const OPSYN_SYSTEM_PROMPT =
  'You are an AI Workflow Builder for OPSYN (Activepieces-based). ' +
  'Return ONLY a valid JSON object with keys: displayName, trigger, schemaVersion.';

/**
 * Extended prompt
 */
export const OPSYN_SYSTEM_PROMPT_EXTENDED = `You are an AI Workflow Builder for OPSYN (Activepieces-based).

CRITICAL RULES:
1. Return ONLY valid JSON
2. Include displayName, trigger, schemaVersion
3. Use ROUTER for conditionals
4. No UI-only fields
5. No markdown, no text`;

/**
 * FlowTemplate interface
 */
export interface FlowTemplate {
  name: string;
  description: string;
  tags: string[];
  pieces: string[];
  template: Flow;
  blogUrl?: string;
}

/**
 * Extract JSON safely
 */
function extractJson(raw: string): unknown {
  const cleaned = raw
    .replace(/```json/g, '')
    .replace(/```/g, '')
    .trim();

  const start = cleaned.indexOf('{');
  const end = cleaned.lastIndexOf('}');
  if (start === -1 || end === -1) {
    throw new Error('Invalid JSON output');
  }

  return JSON.parse(cleaned.substring(start, end + 1));
}

/**
 * Extract used pieces
 */
function extractPieces(flow: Flow): string[] {
  const pieces = new Set<string>();

  const walk = (obj: any) => {
    if (!obj || typeof obj !== 'object') return;
    if (obj.settings?.pieceName) pieces.add(obj.settings.pieceName);
    Object.values(obj).forEach(walk);
  };

  walk(flow);
  return [...pieces];
}

/**
 * Convert to FlowTemplate
 */
function toTemplate(flow: Flow): FlowTemplate {
  return {
    name: flow.displayName || 'Untitled Flow',
    description: 'Generated by OPSYN',
    tags: [],
    pieces: extractPieces(flow),
    template: flow,
  };
}

/**
 * MAIN PIPELINE
 */
export async function processModelOutputToFlowTemplate(
  raw: string
): Promise<string> {
  const extracted = extractJson(raw);
  const flow = extracted as unknown as Flow;

  if (!flow.displayName) throw new Error('Missing displayName');
  if (!flow.trigger) throw new Error('Missing trigger');

  return JSON.stringify(toTemplate(flow), null, 2);
}

/**
 * Object version
 */
export async function processModelOutputToFlowTemplateObject(
  raw: string
): Promise<FlowTemplate> {
  return JSON.parse(await processModelOutputToFlowTemplate(raw));
}

/**
 * Prompt generator
 */
export function generateFullPrompt(
  userPrompt: string,
  extended = false
): string {
  return `${extended ? OPSYN_SYSTEM_PROMPT_EXTENDED : OPSYN_SYSTEM_PROMPT}

User Request: ${userPrompt}`;
}
